### Working with dates

# Dates can be a challenge to work with in any programming language, but thanks to the lubridate package, 
# working with dates in R isn't so bad. Since this course is about cleaning data, 
# we only cover the most basic functions from lubridate to help us standardize the format of dates and times in our data.

# As you saw in the video, these functions combine the letters y, m, d, h, m, s, 
# which stand for year, month, day, hour, minute, and second, respectively. 
# The order of the letters in the function should match the order of the date/time you are attempting to read in, 
# although not all combinations are valid. 
# Notice that the functions are "smart" in that they are capable of parsing multiple formats.

### Instructions

# We have loaded a dataset called students2 into your workspace. students2 is similar to students, 
# except now instead of an age for each student, we have a (hypothetical) date of birth in the dob column. 
# There's another new column called nurse_visit, 
# which gives a timestamp for each student's most recent visit to the school nurse.

# Preview students2 with str(). Notice that dob and nurse_visit are both stored as character.
# Load the lubridate package.
# Print "17 Sep 2015" as a date.
# Print "July 15, 2012 12:56" as a date and time (note there are hours and minutes, but no seconds!).
# Coerce dob to a date (with no time).
# Coerce nurse_visit to a date and time.
# Use str() to see the changes to students2.

### R

> # Preview students2 with str()
> str(students2)
'data.frame':	395 obs. of  33 variables:
 $ X          : int  1 2 3 4 5 6 7 8 9 10 ...
 $ school     : chr  "GP" "GP" "GP" "GP" ...
 $ sex        : chr  "F" "F" "F" "F" ...
 $ dob        : chr  "2000-06-05" "1999-11-25" "1998-02-02" "1997-12-20" ...
 $ address    : chr  "U" "U" "U" "U" ...
 $ famsize    : chr  "GT3" "GT3" "LE3" "GT3" ...
 $ Pstatus    : chr  "A" "T" "T" "T" ...
 $ Medu       : int  4 1 1 4 3 4 2 4 3 3 ...
 $ Fedu       : int  4 1 1 2 3 3 2 4 2 4 ...
 $ Mjob       : chr  "at_home" "at_home" "at_home" "health" ...
 $ Fjob       : chr  "teacher" "other" "other" "services" ...
 $ reason     : chr  "course" "course" "other" "home" ...
 $ guardian   : chr  "mother" "father" "mother" "mother" ...
 $ traveltime : int  2 1 1 1 1 1 1 2 1 1 ...
 $ studytime  : int  2 2 2 3 2 2 2 2 2 2 ...
 $ failures   : int  0 0 3 0 0 0 0 0 0 0 ...
 $ schoolsup  : chr  "yes" "no" "yes" "no" ...
 $ famsup     : chr  "no" "yes" "no" "yes" ...
 $ paid       : chr  "no" "no" "yes" "yes" ...
 $ activities : chr  "no" "no" "no" "yes" ...
 $ nursery    : chr  "yes" "no" "yes" "yes" ...
 $ higher     : chr  "yes" "yes" "yes" "yes" ...
 $ internet   : chr  "no" "yes" "yes" "yes" ...
 $ romantic   : chr  "no" "no" "no" "yes" ...
 $ famrel     : int  4 5 4 3 4 5 4 4 4 5 ...
 $ freetime   : int  3 3 3 2 3 4 4 1 2 5 ...
 $ goout      : int  4 3 2 2 2 2 4 4 2 1 ...
 $ Dalc       : int  1 1 2 1 1 1 1 1 1 1 ...
 $ Walc       : int  1 1 3 1 2 2 1 1 1 1 ...
 $ health     : int  3 3 3 5 5 5 3 1 1 5 ...
 $ nurse_visit: chr  "2014-04-10 14:59:54" "2015-03-12 14:59:54" "2015-09-21 14:59:54" "2015-09-03 14:59:54" ...
 $ absences   : int  6 4 10 2 4 10 0 6 0 0 ...
 $ Grades     : chr  "5/6/6" "5/5/6" "7/8/10" "15/14/15" ...
> 
> # Load the lubridate package
> library(lubridate)
> 
> # Parse as date
> dmy("17 Sep 2015")
[1] "2015-09-17"
> 
> # Parse as date and time (with no seconds!)
> mdy_hm("July 15, 2012 12:56")
[1] "2012-07-15 12:56:00 UTC"
> 
> # Coerce dob to a date (with no time)
> students2$dob <- ymd(students2$dob)
> 
> # Coerce nurse_visit to a date and time
> students2$nurse_visit <- ymd_hms(students2$nurse_visit)
> 
> # Look at students2 once more with str()
> str(students2)
'data.frame':	395 obs. of  33 variables:
 $ X          : int  1 2 3 4 5 6 7 8 9 10 ...
 $ school     : chr  "GP" "GP" "GP" "GP" ...
 $ sex        : chr  "F" "F" "F" "F" ...
 $ dob        : Date, format: "2000-06-05" "1999-11-25" ...
 $ address    : chr  "U" "U" "U" "U" ...
 $ famsize    : chr  "GT3" "GT3" "LE3" "GT3" ...
 $ Pstatus    : chr  "A" "T" "T" "T" ...
 $ Medu       : int  4 1 1 4 3 4 2 4 3 3 ...
 $ Fedu       : int  4 1 1 2 3 3 2 4 2 4 ...
 $ Mjob       : chr  "at_home" "at_home" "at_home" "health" ...
 $ Fjob       : chr  "teacher" "other" "other" "services" ...
 $ reason     : chr  "course" "course" "other" "home" ...
 $ guardian   : chr  "mother" "father" "mother" "mother" ...
 $ traveltime : int  2 1 1 1 1 1 1 2 1 1 ...
 $ studytime  : int  2 2 2 3 2 2 2 2 2 2 ...
 $ failures   : int  0 0 3 0 0 0 0 0 0 0 ...
 $ schoolsup  : chr  "yes" "no" "yes" "no" ...
 $ famsup     : chr  "no" "yes" "no" "yes" ...
 $ paid       : chr  "no" "no" "yes" "yes" ...
 $ activities : chr  "no" "no" "no" "yes" ...
 $ nursery    : chr  "yes" "no" "yes" "yes" ...
 $ higher     : chr  "yes" "yes" "yes" "yes" ...
 $ internet   : chr  "no" "yes" "yes" "yes" ...
 $ romantic   : chr  "no" "no" "no" "yes" ...
 $ famrel     : int  4 5 4 3 4 5 4 4 4 5 ...
 $ freetime   : int  3 3 3 2 3 4 4 1 2 5 ...
 $ goout      : int  4 3 2 2 2 2 4 4 2 1 ...
 $ Dalc       : int  1 1 2 1 1 1 1 1 1 1 ...
 $ Walc       : int  1 1 3 1 2 2 1 1 1 1 ...
 $ health     : int  3 3 3 5 5 5 3 1 1 5 ...
 $ nurse_visit: POSIXct, format: "2014-04-10 14:59:54" "2015-03-12 14:59:54" ...
 $ absences   : int  6 4 10 2 4 10 0 6 0 0 ...
 $ Grades     : chr  "5/6/6" "5/5/6" "7/8/10" "15/14/15" ...
> 
